#Andrew Petersen

print("SDLC is Software Development Life Cycle")
print("This is the repeatable steps of software development")
print("")
print("Step 1: Requirement analysis")
print("    Understand what the program needs to do")
print("Step 2: Planning/Design")
print("    Map out the algorithm (pseudocode, flowcharts)")
print("Step 3: Implementation")
print("    Write the code with comments")
print("Step 4: Testing")
print("    Check for errors & correct results")
print("Step 5: Release and Maintenance")
print("    Share it - and keep fixing/updating it")
print("")
print("Algorithm: a step-by-step set of instructions for solving a problem, written in a way a computer (or a person) can follow exactly")
print("Software Development Life Cycle (SDLC): the repeatable set of stages a program goes through, from idea to finished, maintained product")
print("Pseudocode: a way of planning an algorithm using plain, structured language instead of actual code syntax — it lets you plan the logic before worrying about Python-specific rules")
print("")
print("Why does reliable software matter")
print("    Unreliable software can cost peopl money, time, or even safety.")
print("    A bug can cost real money")
print("Requirement analysis")
print("    3 questions:")
print("     what is the problem?")
print("     What inputs does it need?")
print("     What outputs shuld it produce?")
print("YOU CANNOT BUILD A PROGRAM IF THIS STEP IS SKIPPED")